/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import java.sql.*;
import javax.swing.*;


/**
 *
 * @author Arshita Marwaha
 */
public class easy extends javax.swing.JFrame {

    /**
     * Creates new form easy
     */
    private String name;
    private int chance = 8;
    private int wordLength = 0;
    private int textFilled = 0;
    private ResultSet rs;
    
    public easy() {
        initComponents();
        jTextField1.setVisible(false);
        jTextField2.setVisible(false);
        jTextField3.setVisible(false);
        jTextField4.setVisible(false);
        jTextField5.setVisible(false);
        jTextField6.setVisible(false);
        jTextField7.setVisible(false);
        jTextField8.setVisible(false);
        jTextField9.setVisible(false);
        jLabel1.setVisible(false);
        jLabel2.setVisible(false);
        jLabel3.setVisible(false);
        jLabel4.setVisible(false);
        jLabel5.setVisible(false);
        jLabel6.setVisible(false);
        jLabel7.setVisible(false);
        jLabel8.setVisible(false);
        jLabel9.setVisible(false);
        
        try 
        {
            Class.forName("com.mysql.jdbc.Driver"); 
            Connection con= DriverManager.getConnection("jdbc:mysql://localhost:3306/hangman","root","gungun@01");
            Statement stmt = con.createStatement(); 
            String query = "select moviename from moveasy;" ;
            rs = stmt.executeQuery(query);   
            rs.first();
            if (rs.getString(1).equals(""))
            {
                JOptionPane.showMessageDialog(null, "No names in database");
                System.exit(0);
            }
            else
            {
               name = rs.getString(1);
            }
            
        } catch (Exception e ){JOptionPane.showMessageDialog(null, e.getMessage());}
          
           wordLength = name.length();
           System.out.print(wordLength);
           int b = 9-wordLength;
           System.out.print(b);
          
           switch (b) {   case 0 : jTextField9.setVisible(true);
              
                         case 1 : jTextField8.setVisible(true);
                         case 2 : jTextField7.setVisible(true);
                          case 3 : jTextField6.setVisible(true);
                          case 4 : jTextField5.setVisible(true);
                          case 5 : jTextField4.setVisible(true);
                          case 6 : jTextField3.setVisible(true);
                          case 7 : jTextField2.setVisible(true);
                          case 8 : jTextField1.setVisible(true);
                                    jTextField1.grabFocus();
        
        }   
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(972, 706));
        setResizable(false);

        jTextField1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField1FocusLost(evt);
            }
        });
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jButton1.setText("Submit");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton1MousePressed(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTextField2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField2FocusLost(evt);
            }
        });

        jTextField3.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField3FocusLost(evt);
            }
        });

        jTextField4.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField4FocusLost(evt);
            }
        });

        jTextField5.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField5FocusLost(evt);
            }
        });

        jTextField6.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField6FocusLost(evt);
            }
        });

        jTextField7.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField7FocusLost(evt);
            }
        });

        jTextField8.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField8FocusLost(evt);
            }
        });

        jTextField9.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField9FocusLost(evt);
            }
        });

        jButton2.setText("Exit");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton2MousePressed(evt);
            }
        });

        jButton3.setText("Next");
        jButton3.setToolTipText("");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Arshita\\projects\\ip_investigatory_final\\head.png")); // NOI18N

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Arshita\\projects\\ip_investigatory_final\\right leg left hand.png")); // NOI18N

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Arshita\\projects\\ip_investigatory_final\\left leg right hand.png")); // NOI18N

        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Arshita\\projects\\ip_investigatory_final\\left leg right hand.png")); // NOI18N

        jLabel5.setIcon(new javax.swing.ImageIcon("C:\\Arshita\\projects\\ip_investigatory_final\\right leg left hand.png")); // NOI18N

        jLabel6.setIcon(new javax.swing.ImageIcon("C:\\Arshita\\projects\\ip_investigatory_final\\body.png")); // NOI18N

        jLabel7.setIcon(new javax.swing.ImageIcon("C:\\Arshita\\projects\\ip_investigatory_final\\body.png")); // NOI18N

        jLabel8.setIcon(new javax.swing.ImageIcon("C:\\Arshita\\projects\\ip_investigatory_final\\stand sleeping.png")); // NOI18N

        jLabel9.setIcon(new javax.swing.ImageIcon("C:\\Arshita\\projects\\ip_investigatory_final\\body.png")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addGap(47, 47, 47))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(69, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(126, 126, 126)
                        .addComponent(jLabel1)
                        .addGap(162, 162, 162))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton2)
                                .addGap(68, 68, 68)
                                .addComponent(jButton3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel2))
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(79, 79, 79)
                                .addComponent(jLabel7)))
                        .addGap(42, 42, 42))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(35, 35, 35)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jButton2)
                                            .addComponent(jButton1)
                                            .addComponent(jButton3))))
                                .addGap(47, 47, 47)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(63, 63, 63)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(59, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ManageChance()
    {
       chance = chance - 1;
        switch (chance){
            case 7 : 
                jLabel7.setVisible(true);
                jLabel8.setVisible(true);
                jLabel9.setVisible(true);
                break;
            case 6 : 
                jLabel1.setVisible(true);
                
                break;
            case 5 : 
                
                jLabel3.setVisible(true);
                break;
            case 4 : 
                
                jLabel5.setVisible(true);
                break;
            case 3: 
                jLabel6.setVisible(true);
                break;
            case 2 : 
                jLabel4.setVisible(true);
                break;
            case 1 : 
                jLabel2.setVisible(true);
                JOptionPane.showMessageDialog(null, "Chances over. You have lost the game");
                System.exit(0);
        }
    
    }
    
    int SanityCheckOfFields()
    {
       String empty = "";
       int notFilled = 0;
       if (empty.equalsIgnoreCase(jTextField1.getText()))
       {
           jTextField1.grabFocus();
           empty = "";
           notFilled = 1;
       }
       else if (empty.equalsIgnoreCase(jTextField2.getText()))
        {
          jTextField2.grabFocus();
          empty = "";  
          notFilled = 2;
        }
       else if (empty.equalsIgnoreCase(jTextField3.getText()))
        {
          jTextField3.grabFocus();
          empty = "";  
          notFilled = 3;
        }
    else if (empty.equalsIgnoreCase(jTextField4.getText()))
        {
          jTextField4.grabFocus();
          empty = "";  
          notFilled = 4;
        }
    else if (empty.equalsIgnoreCase(jTextField5.getText()))
        {
          jTextField5.grabFocus();
          empty = "";
          notFilled = 5;
        }
       else if (empty.equalsIgnoreCase(jTextField6.getText()))
        {
          jTextField6.grabFocus();
          empty = ""; 
          notFilled = 6;
        }
       else if (empty.equalsIgnoreCase(jTextField7.getText()))
        {
          jTextField7.grabFocus();
          empty = "";
          notFilled = 7;
        }
       else if (empty.equalsIgnoreCase(jTextField8.getText()))
        {
          jTextField8.grabFocus();
          empty = "";  
          notFilled = 8;
        }
       else if (empty.equalsIgnoreCase(jTextField9.getText()))
        {
          jTextField9.grabFocus();
          empty = "";  
          notFilled = 9;
        }
       return notFilled;
    }
    
    void setTextAndFocus(JTextField txtField1, JTextField txtField2, String str)
    {
        txtField1.setText(str.toUpperCase());
        txtField1.setEditable(false);
        txtField1.setFocusable(false);
        txtField2.grabFocus();
     
    }
            
    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField1FocusLost
        // TODO add your handling code here:
       if (SanityCheckOfFields()== 1)
       {
           return;
       }
       else
       {
       String charVal = jTextField1.getText(); 
       String c ;
        c = name.substring(0,1);
        if (c.equalsIgnoreCase(charVal))
        {
            setTextAndFocus(jTextField1, jTextField2, c);
            textFilled = 1;
        }
        else
        { 
           ManageChance();
           jTextField1.setText("");
           jTextField1.grabFocus();

        } 
       }
    }//GEN-LAST:event_jTextField1FocusLost

    private void jTextField2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField2FocusLost
        // TODO add your handling code here:
       if (SanityCheckOfFields()== 1 || SanityCheckOfFields()== 2)
       {
           return;
       }
       else 
       {
       String charVal = jTextField2.getText(); 
       String c ;
        c = name.substring(1,2);
        if (c.equalsIgnoreCase(charVal))
        {
            setTextAndFocus(jTextField2, jTextField3, c);
            textFilled = 2;
        }
        else
        { 
           ManageChance();
           jTextField2.setText("");
           jTextField2.grabFocus();

        } 
       }
    }//GEN-LAST:event_jTextField2FocusLost

    private void jTextField3FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField3FocusLost
        // TODO add your handling code here:
        if (SanityCheckOfFields()== 3)
        {
            return;
        }
        else 
        {
            String empty = "";
                 if (empty.equalsIgnoreCase(jTextField2.getText()))
                {
                    jTextField2.grabFocus();
                }
                else
                {
                 String charVal = jTextField3.getText(); 
                String c ;
                 c = name.substring(2,3);
                 if (c.equalsIgnoreCase(charVal))
                 {
                     setTextAndFocus(jTextField3, jTextField4, c);
                     textFilled = 3;
                 }
                 else
                 { 
                    ManageChance();
                    jTextField3.setText("");
                    jTextField3.grabFocus();
                 }
                }
        }
    }//GEN-LAST:event_jTextField3FocusLost

    private void jTextField4FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField4FocusLost
        // TODO add your handling code here:
        if (SanityCheckOfFields()== 4)
        {
            return;
        }
        else 
        {
            String empty = "";
             if (empty.equalsIgnoreCase(jTextField3.getText()))
            {
                jTextField3.grabFocus();
            }
            else
            {
            String charVal = jTextField4.getText(); 
            String c ;
             c = name.substring(3,4);
             if (c.equalsIgnoreCase(charVal))
             {
                setTextAndFocus(jTextField4, jTextField5, c);
                textFilled = 4;
             }
             else
             { 
                ManageChance();
                jTextField4.setText("");
                jTextField4.grabFocus();
             }
            }
       }    
    }//GEN-LAST:event_jTextField4FocusLost

    private void jTextField5FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField5FocusLost
        // TODO add your handling code here:
        if (SanityCheckOfFields()== 5)
        {
            return;
        }
        else 
        {
            String empty = "";
             if (empty.equalsIgnoreCase(jTextField4.getText()))
            {
                jTextField4.grabFocus();
            }
            else
            {
            String charVal = jTextField5.getText(); 
            String c ;
             c = name.substring(4,5);
             if (c.equalsIgnoreCase(charVal))
             {
                 setTextAndFocus(jTextField5, jTextField6, c);
                 textFilled = 5;
             }
             else
             { 
                ManageChance();
                jTextField5.setText("");
                jTextField5.grabFocus();
             }
            }
        }
    }//GEN-LAST:event_jTextField5FocusLost

    private void jTextField6FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField6FocusLost
        // TODO add your handling code here:
        if (SanityCheckOfFields()== 6)
        {
            return;
        }
        else 
        {
            String empty = "";
             if (empty.equalsIgnoreCase(jTextField5.getText()))
            {
                jTextField5.grabFocus();
            }
            else
            {
            String charVal = jTextField6.getText(); 
            String c ;
             c = name.substring(5,6);
             if (c.equalsIgnoreCase(charVal))
             {
                    setTextAndFocus(jTextField6, jTextField7, c);
                    textFilled = 6;
                    
             }
             else
             { 
                ManageChance();
                jTextField6.setText("");
                jTextField6.grabFocus();
             }
            }
        }
    }//GEN-LAST:event_jTextField6FocusLost

    private void jTextField7FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField7FocusLost
        // TODO add your handling code here:
        if (SanityCheckOfFields()== 7)
        {
            return;
        }
        else 
        {
            String empty = "";
             if (empty.equalsIgnoreCase(jTextField6.getText()))
            {
                jTextField6.grabFocus();
            }
            else
            {
            String charVal = jTextField7.getText(); 
            String c ;
             c = name.substring(6,7);
             if (c.equalsIgnoreCase(charVal))
             {
                 setTextAndFocus(jTextField7, jTextField8, c);
                 textFilled = 7;
             }
             else
             { 
                ManageChance();
                jTextField7.setText("");
                jTextField7.grabFocus();
             }
            }
        }
    }//GEN-LAST:event_jTextField7FocusLost

    private void jTextField8FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField8FocusLost
        // TODO add your handling code here:
        if (SanityCheckOfFields()== 8)
        {
            return;
        }
        else 
        {
            String empty = "";
             if (empty.equalsIgnoreCase(jTextField7.getText()))
            {
                jTextField7.grabFocus();
            }
            else
            {
            String charVal = jTextField8.getText(); 
            String c ;
             c = name.substring(7,8);
             if (c.equalsIgnoreCase(charVal))
             {
                setTextAndFocus(jTextField8, jTextField9, c);
                textFilled = 8;
             }
             else
             { 
                ManageChance();
                jTextField8.setText("");
                jTextField8.grabFocus();
             }
            }
        }
    }//GEN-LAST:event_jTextField8FocusLost

    private void jTextField9FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField9FocusLost
        // TODO add your handling code here:
        if (SanityCheckOfFields()== 9)
        {
            return;
        }
        else 
        {
            String empty = "";
             if (empty.equalsIgnoreCase(jTextField8.getText()))
            {
                jTextField8.grabFocus();
            }
            else
            {
             String charVal = jTextField9.getText(); 
            String c ;
             c = name.substring(8,9);
             if (c.equalsIgnoreCase(charVal))
             {
                 setTextAndFocus(jTextField9, jTextField9, c);
                 textFilled = 9;
         }
             else
             { 
                ManageChance();
                jTextField9.setText("");
                jTextField9.grabFocus();
             }
            }
        }
    }//GEN-LAST:event_jTextField9FocusLost

    private void jButton1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MousePressed
        // TODO add your handling code here:
        if (textFilled != wordLength)
        {
            JOptionPane.showMessageDialog(null, "Please enter name letter to play the game");
        }
        else 
        {
            JOptionPane.showMessageDialog(null, "You have won the game. Press Next to Play Another round");            
        }
    }//GEN-LAST:event_jButton1MousePressed

    private void jButton2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MousePressed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Exiting game");
        System.exit(0);
    }//GEN-LAST:event_jButton2MousePressed

    void RefreshTextFields(JTextField jTxtField)
    {
        jTxtField.setVisible(true);
        jTxtField.setFocusable(true);
        jTxtField.setText("");
        jTxtField.setEditable(true);
    }
    
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        chance = 8;
        wordLength = 0;
        textFilled = 0;
        
        //initComponents();
        jTextField1.setVisible(false);
        jTextField2.setVisible(false);
        jTextField3.setVisible(false);
        jTextField4.setVisible(false);
        jTextField5.setVisible(false);
        jTextField6.setVisible(false);
        jTextField7.setVisible(false);
        jTextField8.setVisible(false);
        jTextField9.setVisible(false);
        jLabel1.setVisible(false);
        jLabel2.setVisible(false);
        jLabel3.setVisible(false);
        jLabel4.setVisible(false);
        jLabel5.setVisible(false);
        jLabel6.setVisible(false);
        jLabel7.setVisible(false);
        
        try
        {
            //while (rs.next())
            //{
            if (rs.next())
            {
                name = rs.getString(1);
                wordLength = name.length();
                while (wordLength > 9)
                {
                    rs.next();
                    name = rs.getString(1);
                    wordLength = name.length();
                }
            }
            else
            {
                JOptionPane.showMessageDialog(null, "You have have reached end of database. Starting again");
                rs.first();
                name = rs.getString(1);
                wordLength = name.length();
            }
        
            //}
        } catch (Exception e ){JOptionPane.showMessageDialog(null, e.getMessage());}   
          
        int b;
        b = 9-wordLength;
        
        
           System.out.print(b);
          
           switch (b) {  case 0 : RefreshTextFields(jTextField9);              
                         case 1 : RefreshTextFields(jTextField8);
                         case 2 : RefreshTextFields(jTextField7);
                         case 3 : RefreshTextFields(jTextField6);
                         case 4 : RefreshTextFields(jTextField5);
                         case 5 : RefreshTextFields(jTextField4);
                         case 6 : RefreshTextFields(jTextField3);
                         case 7 : RefreshTextFields(jTextField2);
                         case 8 : RefreshTextFields(jTextField1);
                                  jTextField1.grabFocus();
                         
        
        }   
        
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(easy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(easy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(easy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(easy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new easy().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables
}
