
import java.sql.ResultSet;
import java.sql.*;
import javax.swing.*;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Arshita Marwaha
 */
public class medium extends javax.swing.JFrame {

    /**
     * Creates new form easy
     */
    private String name;
    private int chance = 8;
    private int wordLength = 0;
    private int textFilled = 0;
    private ResultSet rs;
    
    /**
     * Creates new form medium
     */
    public medium() {
        initComponents();
        jTextField1.setVisible(false);
        jTextField2.setVisible(false);
        jTextField3.setVisible(false);
        jTextField4.setVisible(false);
        jTextField5.setVisible(false);
        jTextField6.setVisible(false);
        jTextField7.setVisible(false);
        jTextField8.setVisible(false);
        jTextField9.setVisible(false);
        jTextField10.setVisible(false);
        jTextField11.setVisible(false);
        jTextField12.setVisible(false);
        jLabel1.setVisible(false);
        jLabel2.setVisible(false);
        jLabel3.setVisible(false);
        jLabel4.setVisible(false);
        jLabel5.setVisible(false);
        jLabel6.setVisible(false);
        jLabel7.setVisible(false);
        
        try 
        {
            Class.forName("com.mysql.jdbc.Driver"); 
            Connection con= DriverManager.getConnection("jdbc:mysql://localhost/hangman","root","gungun@01");
            Statement stmt = con.createStatement(); 
            String query = "select movie_name from gamemed;" ;
            rs = stmt.executeQuery(query);   
            rs.first();
            if (rs.getString(1).equals(""))
            {
                JOptionPane.showMessageDialog(null, "No names in database");
                System.exit(0);
            }
            else
            {
               name = rs.getString(1);
            }
            
        } catch (Exception e ){JOptionPane.showMessageDialog(null, e.getMessage());}
          
           wordLength = name.length();
           System.out.print(wordLength);
           int b = 12-wordLength;
           System.out.print(b);
          
           switch (b) {   case 0 : jTextField12.setVisible(true);
              
                         case 1 : jTextField11.setVisible(true);
                         case 2 : jTextField10.setVisible(true);
                         case 3 : jTextField9.setVisible(true);
                         case 4 : jTextField8.setVisible(true);
                         case 5 : jTextField7.setVisible(true);
                         case 6 : jTextField6.setVisible(true);
                         case 7 : jTextField5.setVisible(true);
                         case 8 : jTextField4.setVisible(true);
                         case 9 : jTextField3.setVisible(true);
                         case 10 : jTextField2.setVisible(true);
                         case 11 : jTextField1.setVisible(true); 
                             jTextField1.grabFocus();
        }   
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jTextField11 = new javax.swing.JTextField();
        jTextField12 = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(972, 706));
        setResizable(false);

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jTextField1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField1FocusLost(evt);
            }
        });

        jButton1.setText("Submit");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton1MousePressed(evt);
            }
        });

        jTextField2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField2FocusLost(evt);
            }
        });

        jTextField3.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField3FocusLost(evt);
            }
        });

        jTextField4.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField4FocusLost(evt);
            }
        });

        jTextField5.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField5FocusLost(evt);
            }
        });

        jTextField6.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField6FocusLost(evt);
            }
        });

        jTextField7.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField7FocusLost(evt);
            }
        });

        jTextField8.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField8FocusLost(evt);
            }
        });

        jTextField9.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField9FocusLost(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Arshita\\ProjectIcons\\circle.png")); // NOI18N

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Arshita\\ProjectIcons\\stand.png")); // NOI18N

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Arshita\\ProjectIcons\\standwidth.png")); // NOI18N

        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Arshita\\ProjectIcons\\standlength.png")); // NOI18N

        jLabel5.setIcon(new javax.swing.ImageIcon("C:\\Arshita\\ProjectIcons\\body.png")); // NOI18N

        jLabel6.setIcon(new javax.swing.ImageIcon("C:\\Arshita\\ProjectIcons\\lefthand.png")); // NOI18N

        jLabel7.setIcon(new javax.swing.ImageIcon("C:\\Arshita\\ProjectIcons\\righthand.png")); // NOI18N

        jLabel8.setIcon(new javax.swing.ImageIcon("C:\\Arshita\\ProjectIcons\\leftleg.png")); // NOI18N

        jLabel9.setIcon(new javax.swing.ImageIcon("C:\\Arshita\\ProjectIcons\\rightleg.png")); // NOI18N

        jButton2.setText("Exit");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton2MousePressed(evt);
            }
        });

        jButton3.setText("Next");
        jButton3.setToolTipText("");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jTextField11.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField11FocusLost(evt);
            }
        });

        jTextField12.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField12FocusLost(evt);
            }
        });

        jTextField10.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField10FocusLost(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jButton1))
                        .addGap(18, 18, 18)
                        .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addComponent(jButton2)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 234, Short.MAX_VALUE)
                                .addComponent(jLabel1)
                                .addGap(28, 28, 28))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jButton3)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextField12, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addGap(65, 65, 65))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(102, 102, 102)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(113, 113, 113)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTextField12, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(1, 1, 1)
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(51, 51, 51)
                                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addGap(61, 61, 61)
                                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton2)
                            .addComponent(jButton1)
                            .addComponent(jButton3))))
                .addContainerGap(681, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField10FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField10FocusLost
        // TODO add your handling code here:
        if (SanityCheckOfFields()== 10)
        {
            return;
        }
        else 
        {
            String empty = "";
             if (empty.equalsIgnoreCase(jTextField9.getText()))
            {
                jTextField9.grabFocus();
            }
            else
            {
            String charVal = jTextField10.getText(); 
            String c ;
             c = name.substring(9,10);
             if (c.equalsIgnoreCase(charVal))
             {
                setTextAndFocus(jTextField10, jTextField11, c);
                textFilled = 10;
             }
             else
             { 
                ManageChance();
                jTextField10.setText("");
                jTextField10.grabFocus();
             }
            }
        }        
    }//GEN-LAST:event_jTextField10FocusLost

    private void jTextField11FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField11FocusLost
        // TODO add your handling code here:
        if (SanityCheckOfFields()== 11)
        {
            return;
        }
        else 
        {
            String empty = "";
             if (empty.equalsIgnoreCase(jTextField10.getText()))
            {
                jTextField10.grabFocus();
            }
            else
            {
            String charVal = jTextField11.getText(); 
            String c ;
             c = name.substring(10,11);
             if (c.equalsIgnoreCase(charVal))
             {
                setTextAndFocus(jTextField11, jTextField12, c);
                textFilled = 11;
             }
             else
             { 
                ManageChance();
                jTextField11.setText("");
                jTextField11.grabFocus();
             }
            }
        }
        
    }//GEN-LAST:event_jTextField11FocusLost

    private void jTextField12FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField12FocusLost
        // TODO add your handling code here:
        if (SanityCheckOfFields()== 12)
        {
            return;
        }
        else 
        {
            String empty = "";
             if (empty.equalsIgnoreCase(jTextField11.getText()))
            {
                jTextField11.grabFocus();
            }
            else
            {
            String charVal = jTextField12.getText(); 
            String c ;
             c = name.substring(11,12);
             if (c.equalsIgnoreCase(charVal))
             {
                setTextAndFocus(jTextField12, jTextField12, c);
                textFilled = 12;
             }
             else
             { 
                ManageChance();
                jTextField12.setText("");
                jTextField12.grabFocus();
             }
            }
        }
        
    }//GEN-LAST:event_jTextField12FocusLost
private void ManageChance()
    {
       chance = chance - 1;
        switch (chance){
            case 7 : 
                jLabel1.setVisible(true);
                break;
            case 6 : 
                jLabel5.setVisible(true);
                break;
            case 5 : 
                jLabel3.setVisible(true);
                break;
            case 4 : 
                jLabel2.setVisible(true);
                break;
            case 3: 
                jLabel7.setVisible(true);
                break;
            case 2 : 
                jLabel4.setVisible(true);
                break;
            case 1 : 
                jLabel6.setVisible(true);
                JOptionPane.showMessageDialog(null, "Chances over. You have lost the game");
                System.exit(0);
        }
    
    }
    
    int SanityCheckOfFields()
    {
       String empty = "";
       int notFilled = 0;
       if (empty.equalsIgnoreCase(jTextField1.getText()))
       {
           jTextField1.grabFocus();
           empty = "";
           notFilled = 1;
       }
       else if (empty.equalsIgnoreCase(jTextField2.getText()))
        {
          jTextField2.grabFocus();
          empty = "";  
          notFilled = 2;
        }
       else if (empty.equalsIgnoreCase(jTextField3.getText()))
        {
          jTextField3.grabFocus();
          empty = "";  
          notFilled = 3;
        }
    else if (empty.equalsIgnoreCase(jTextField4.getText()))
        {
          jTextField4.grabFocus();
          empty = "";  
          notFilled = 4;
        }
    else if (empty.equalsIgnoreCase(jTextField5.getText()))
        {
          jTextField5.grabFocus();
          empty = "";
          notFilled = 5;
        }
       else if (empty.equalsIgnoreCase(jTextField6.getText()))
        {
          jTextField6.grabFocus();
          empty = ""; 
          notFilled = 6;
        }
       else if (empty.equalsIgnoreCase(jTextField7.getText()))
        {
          jTextField7.grabFocus();
          empty = "";
          notFilled = 7;
        }
       else if (empty.equalsIgnoreCase(jTextField8.getText()))
        {
          jTextField8.grabFocus();
          empty = "";  
          notFilled = 8;
        }
       else if (empty.equalsIgnoreCase(jTextField9.getText()))
        {
          jTextField9.grabFocus();
          empty = "";  
          notFilled = 9;
        }
       else if (empty.equalsIgnoreCase(jTextField10.getText()))
        {
          jTextField10.grabFocus();
          empty = "";  
          notFilled = 10;
        }
       else if (empty.equalsIgnoreCase(jTextField11.getText()))
        {
          jTextField11.grabFocus();
          empty = "";  
          notFilled = 11;
        }
       else if (empty.equalsIgnoreCase(jTextField12.getText()))
        {
          jTextField12.grabFocus();
          empty = "";  
          notFilled = 12;
        }
       return notFilled;
    }
    
    void setTextAndFocus(JTextField txtField1, JTextField txtField2, String str)
    {
        txtField1.setText(str.toUpperCase());
        txtField1.setEditable(false);
        txtField1.setFocusable(false);
        txtField2.grabFocus();
     
    }
     private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
    }                                           
                                            
    private void jTextField1FocusLost(java.awt.event.FocusEvent evt) {                                      
        // TODO add your handling code here:
       if (SanityCheckOfFields()== 1)
       {
           return;
       }
       else
       {
       String charVal = jTextField1.getText(); 
       String c ;
        c = name.substring(0,1);
        if (c.equalsIgnoreCase(charVal))
        {
            setTextAndFocus(jTextField1, jTextField2, c);
            textFilled = 1;
        }
        else
        { 
           ManageChance();
           jTextField1.setText("");
           jTextField1.grabFocus();

        } 
       }
    }                                     

    private void jTextField2FocusLost(java.awt.event.FocusEvent evt) {                                      
        // TODO add your handling code here:
       if (SanityCheckOfFields()== 1 || SanityCheckOfFields()== 2)
       {
           return;
       }
       else 
       {
       String charVal = jTextField2.getText(); 
       String c ;
        c = name.substring(1,2);
        if (c.equalsIgnoreCase(charVal))
        {
            setTextAndFocus(jTextField2, jTextField3, c);
            textFilled = 2;
        }
        else
        { 
           ManageChance();
           jTextField2.setText("");
           jTextField2.grabFocus();

        } 
       }
    }                                     

    private void jTextField3FocusLost(java.awt.event.FocusEvent evt) {                                      
        // TODO add your handling code here:
        if (SanityCheckOfFields()== 3)
        {
            return;
        }
        else 
        {
            String empty = "";
                 if (empty.equalsIgnoreCase(jTextField2.getText()))
                {
                    jTextField2.grabFocus();
                }
                else
                {
                 String charVal = jTextField3.getText(); 
                String c ;
                 c = name.substring(2,3);
                 if (c.equalsIgnoreCase(charVal))
                 {
                     setTextAndFocus(jTextField3, jTextField4, c);
                     textFilled = 3;
                 }
                 else
                 { 
                    ManageChance();
                    jTextField3.setText("");
                    jTextField3.grabFocus();
                 }
                }
        }
    }                                     

    private void jTextField4FocusLost(java.awt.event.FocusEvent evt) {                                      
        // TODO add your handling code here:
        if (SanityCheckOfFields()== 4)
        {
            return;
        }
        else 
        {
            String empty = "";
             if (empty.equalsIgnoreCase(jTextField3.getText()))
            {
                jTextField3.grabFocus();
            }
            else
            {
            String charVal = jTextField4.getText(); 
            String c ;
             c = name.substring(3,4);
             if (c.equalsIgnoreCase(charVal))
             {
                setTextAndFocus(jTextField4, jTextField5, c);
                textFilled = 4;
             }
             else
             { 
                ManageChance();
                jTextField4.setText("");
                jTextField4.grabFocus();
             }
            }
       }    
    }                                     

    private void jTextField5FocusLost(java.awt.event.FocusEvent evt) {                                      
        // TODO add your handling code here:
        if (SanityCheckOfFields()== 5)
        {
            return;
        }
        else 
        {
            String empty = "";
             if (empty.equalsIgnoreCase(jTextField4.getText()))
            {
                jTextField4.grabFocus();
            }
            else
            {
            String charVal = jTextField5.getText(); 
            String c ;
             c = name.substring(4,5);
             if (c.equalsIgnoreCase(charVal))
             {
                 setTextAndFocus(jTextField5, jTextField6, c);
                 textFilled = 5;
             }
             else
             { 
                ManageChance();
                jTextField5.setText("");
                jTextField5.grabFocus();
             }
            }
        }
    }                                     

    private void jTextField6FocusLost(java.awt.event.FocusEvent evt) {                                      
        // TODO add your handling code here:
        if (SanityCheckOfFields()== 6)
        {
            return;
        }
        else 
        {
            String empty = "";
             if (empty.equalsIgnoreCase(jTextField5.getText()))
            {
                jTextField5.grabFocus();
            }
            else
            {
            String charVal = jTextField6.getText(); 
            String c ;
             c = name.substring(5,6);
             if (c.equalsIgnoreCase(charVal))
             {
                    setTextAndFocus(jTextField6, jTextField7, c);
                    textFilled = 6;
                    
             }
             else
             { 
                ManageChance();
                jTextField6.setText("");
                jTextField6.grabFocus();
             }
            }
        }
    }                                     

    private void jTextField7FocusLost(java.awt.event.FocusEvent evt) {                                      
        // TODO add your handling code here:
        if (SanityCheckOfFields()== 7)
        {
            return;
        }
        else 
        {
            String empty = "";
             if (empty.equalsIgnoreCase(jTextField6.getText()))
            {
                jTextField6.grabFocus();
            }
            else
            {
            String charVal = jTextField7.getText(); 
            String c ;
             c = name.substring(6,7);
             if (c.equalsIgnoreCase(charVal))
             {
                 setTextAndFocus(jTextField7, jTextField8, c);
                 textFilled = 7;
             }
             else
             { 
                ManageChance();
                jTextField7.setText("");
                jTextField7.grabFocus();
             }
            }
        }
    }                                     

    private void jTextField8FocusLost(java.awt.event.FocusEvent evt) {                                      
        // TODO add your handling code here:
        if (SanityCheckOfFields()== 8)
        {
            return;
        }
        else 
        {
            String empty = "";
             if (empty.equalsIgnoreCase(jTextField7.getText()))
            {
                jTextField7.grabFocus();
            }
            else
            {
            String charVal = jTextField8.getText(); 
            String c ;
             c = name.substring(7,8);
             if (c.equalsIgnoreCase(charVal))
             {
                setTextAndFocus(jTextField8, jTextField9, c);
                textFilled = 8;
             }
             else
             { 
                ManageChance();
                jTextField8.setText("");
                jTextField8.grabFocus();
             }
            }
        }
    }                                     

    private void jTextField9FocusLost(java.awt.event.FocusEvent evt) {                                      
        // TODO add your handling code here:
        if (SanityCheckOfFields()== 9)
        {
            return;
        }
        else 
        {
            String empty = "";
             if (empty.equalsIgnoreCase(jTextField8.getText()))
            {
                jTextField8.grabFocus();
            }
            else
            {
             String charVal = jTextField9.getText(); 
            String c ;
             c = name.substring(8,9);
             if (c.equalsIgnoreCase(charVal))
             {
                 setTextAndFocus(jTextField9, jTextField9, c);
                 textFilled = 9;
         }
             else
             { 
                ManageChance();
                jTextField9.setText("");
                jTextField9.grabFocus();
             }
            }
        }
    }
    
   
     
    private void jButton1MousePressed(java.awt.event.MouseEvent evt) {                                      
        // TODO add your handling code here:
        if (textFilled != wordLength)
        {
            JOptionPane.showMessageDialog(null, "Please enter name letter to play the game");
        }
        else 
        {
            JOptionPane.showMessageDialog(null, "You have won the game. Press Next to Play Another round");            
        }
    }                                     

    private void jButton2MousePressed(java.awt.event.MouseEvent evt) {                                      
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Exiting game");
        System.exit(0);
    }                                     

    void RefreshTextFields(JTextField jTxtField)
    {
        jTxtField.setVisible(true);
        jTxtField.setFocusable(true);
        jTxtField.setText("");
        jTxtField.setEditable(true);
    }
    
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
        chance = 8;
        wordLength = 0;
        textFilled = 0;
        
        //initComponents();
        jTextField1.setVisible(false);
        jTextField2.setVisible(false);
        jTextField3.setVisible(false);
        jTextField4.setVisible(false);
        jTextField5.setVisible(false);
        jTextField6.setVisible(false);
        jTextField7.setVisible(false);
        jTextField8.setVisible(false);
        jTextField9.setVisible(false);
        jTextField10.setVisible(false);
        jTextField11.setVisible(false);
        jTextField12.setVisible(false);
        jLabel1.setVisible(false);
        jLabel2.setVisible(false);
        jLabel3.setVisible(false);
        jLabel4.setVisible(false);
        jLabel5.setVisible(false);
        jLabel6.setVisible(false);
        jLabel7.setVisible(false);
        
        try
        {
            //while (rs.next())
            //{
            if (rs.next())
            {
                name = rs.getString(1);
                wordLength = name.length();
                while (wordLength > 12)
                {
                    rs.next();
                    name = rs.getString(1);
                    wordLength = name.length();
                }
            }
            else
            {
                JOptionPane.showMessageDialog(null, "You have have reached end of database. Starting again");
                rs.first();
                name = rs.getString(1);
                wordLength = name.length();
            }
        
            //}
        } catch (Exception e ){JOptionPane.showMessageDialog(null, e.getMessage());}   
          
        int b;
        b = 12-wordLength;
        
        
           System.out.print(b);
          
           switch (b) {  case 0 : RefreshTextFields(jTextField12);              
                         case 1 : RefreshTextFields(jTextField11);
                         case 2 : RefreshTextFields(jTextField10);
                         case 3 : RefreshTextFields(jTextField9);
                         case 4 : RefreshTextFields(jTextField8);
                         case 5 : RefreshTextFields(jTextField7);
                         case 6 : RefreshTextFields(jTextField6);
                         case 7 : RefreshTextFields(jTextField5);
                         case 8 : RefreshTextFields(jTextField4);
                         case 9 : RefreshTextFields(jTextField3);
                         case 10 : RefreshTextFields(jTextField2);
                         case 11 : RefreshTextFields(jTextField1);
                                  jTextField1.grabFocus();
                         
        
        }   
        
        
    }                                        

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(medium.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(medium.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(medium.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(medium.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new medium().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables
}
